updates to pacaur automation, install ssh with no prompt

diff --git a/modules/pacaur b/modules/pacaur
--- a/modules/pacaur
+++ b/modules/pacaur
@@ -1,3 +1,5 @@
+set -e # Quit on error
+
 echo "#####################"
 echo "#   Dependencies    #"
 echo "#####################"
