cd correctly, stop script upon error

diff --git a/arch-linuxSetup b/arch-linuxSetup
--- a/arch-linuxSetup
+++ b/arch-linuxSetup
@@ -1,3 +1,4 @@
+set -e # Stop script upon error
 echo "#####################"
 echo "#   Dependencies    #"
 echo "#####################"
@@ -105,4 +106,4 @@ patch /mnt/etc/pacman.conf < chroot/etc/pacman.conf.patch
 
 #Don't use persistent names
 ln -s /dev/null /mnt/etc/udev/rules.d/80-net-name-slot.rules
-cd server-setup/modules
+cd modules
